version: '3.8'

services:
  db:
    image: postgres:13
    container_name: fitb_ai_db
    restart: always
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5440:5432" 