# Generated by Django 5.1.3 on 2024-11-16 12:15

import django.core.validators
import django.db.models.deletion
import profiles.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/",
                        validators=[
                            profiles.validators.FileValidator(
                                content_types=(
                                    "application/pdf",
                                    "application/msword",
                                    "text/plain",
                                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                ),
                                max_size=5242880,
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("skills", models.ManyToManyField(blank=True, to="profiles.skill")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EqualEmploymentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        choices=[
                            ("Hispanic or Latino", "Hispanic or Latino"),
                            ("White", "White"),
                            ("Black or African American", "Black or African American"),
                            (
                                "Native American or American Indian",
                                "Native American or American Indian",
                            ),
                            ("Asian / Pacific Islander", "Asian / Pacific Islander"),
                            ("Other", "Other"),
                            ("Decline to state", "Decline to state"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Non-Binary", "Non-Binary"),
                            ("Decline to state", "Decline to state"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "authorized_us",
                    models.BooleanField(verbose_name="Authorized to work in US"),
                ),
                (
                    "requires_sponsorship",
                    models.BooleanField(verbose_name="Requires visa sponsorship"),
                ),
                (
                    "disability",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Decline to state", "Decline to state"),
                        ],
                        max_length=20,
                        verbose_name="Do you have a disability?",
                    ),
                ),
                (
                    "veteran_status",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Decline to state", "Decline to state"),
                        ],
                        max_length=20,
                        verbose_name="Are you a protected veteran?",
                    ),
                ),
                (
                    "lgbtq",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Decline to state", "Decline to state"),
                        ],
                        max_length=20,
                        verbose_name="Do you identify as LGBTQ+?",
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equal_employment_data",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equal Employment Data",
                "verbose_name_plural": "Equal Employment Data",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=255)),
                ("major", models.CharField(max_length=255)),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("Bachelor's", "Bachelor's"),
                            ("Master's", "Master's"),
                            ("PhD", "PhD"),
                            ("MBA", "MBA"),
                            ("Associate's", "Associate's"),
                            ("MD", "MD"),
                            ("JD", "JD"),
                            ("Bootcamp", "Bootcamp"),
                            ("Certification", "Certification"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("position_title", models.CharField(max_length=255)),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Internship", "Internship"),
                            ("Contract", "Contract"),
                            ("Freelance", "Freelance"),
                            ("Volunteer", "Volunteer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("currently_working", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("LinkedIn", "LinkedIn"),
                            ("GitHub", "GitHub"),
                            ("Twitter", "Twitter"),
                            ("Portfolio", "Portfolio"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "url",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_profile", "platform")},
            },
        ),
    ]
