# Generated by Django 5.1.3 on 2024-12-23 00:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equalemploymentdata",
            name="ethnicity",
        ),
        migrations.RemoveField(
            model_name="equalemploymentdata",
            name="is_authorized_to_work",
        ),
        migrations.RemoveField(
            model_name="equalemploymentdata",
            name="veteran_status",
        ),
        migrations.RemoveField(
            model_name="equalemploymentdata",
            name="will_require_sponsorship",
        ),
        migrations.AddField(
            model_name="equalemploymentdata",
            name="authorized_canada",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=3,
                verbose_name="Are you authorized to work in Canada?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equalemploymentdata",
            name="authorized_uk",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=3,
                verbose_name="Are you authorized to work in the United Kingdom?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equalemploymentdata",
            name="authorized_us",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=3,
                verbose_name="Are you authorized to work in the US?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equalemploymentdata",
            name="ethnicities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Black/African American", "Black/African American"),
                        ("East Asian", "East Asian"),
                        ("South Asian", "South Asian"),
                        ("Hispanic/Latinx", "Hispanic/Latinx"),
                        ("Southeast Asian", "Southeast Asian"),
                        ("Middle Eastern", "Middle Eastern"),
                        ("African", "African"),
                        ("Native American/Alaskan", "Native American/Alaskan"),
                        (
                            "Native Hawaiian/Other Pacific Islander",
                            "Native Hawaiian/Other Pacific Islander",
                        ),
                        ("White", "White"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="What is your ethnicity? (Select all that apply)",
            ),
        ),
        migrations.AddField(
            model_name="equalemploymentdata",
            name="is_hispanic_latinx",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Hispanic/Latinx"
            ),
        ),
        migrations.AddField(
            model_name="equalemploymentdata",
            name="is_lgbtq",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("Decline to state", "Decline to state"),
                ],
                default="No",
                max_length=20,
                verbose_name="Do you identify as LGBTQ+?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equalemploymentdata",
            name="is_veteran",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("Decline to state", "Decline to state"),
                ],
                default="No",
                max_length=20,
                verbose_name="Are you a veteran?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equalemploymentdata",
            name="requires_sponsorship",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=3,
                verbose_name="Will you now or in the future require sponsorship for employment visa status?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="equalemploymentdata",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Non-Binary", "Non-Binary"),
                    ("Decline to state", "Decline to state"),
                ],
                max_length=20,
                verbose_name="What is your gender?",
            ),
        ),
        migrations.AlterField(
            model_name="equalemploymentdata",
            name="has_disability",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("Decline to state", "Decline to state"),
                ],
                default="No",
                max_length=20,
                verbose_name="Do you have a disability?",
            ),
            preserve_default=False,
        ),
    ]
