# Generated by Django 5.1.3 on 2024-11-28 09:15

import profiles.utils.storage.resume_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=profiles.utils.storage.resume_storage.ResumeStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="s3_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
