# Generated by Django 5.1.3 on 2024-12-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_equalemploymentdata_ethnicity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equalemploymentdata",
            name="authorized_canada",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=3,
                null=True,
                verbose_name="Are you authorized to work in Canada?",
            ),
        ),
        migrations.AlterField(
            model_name="equalemploymentdata",
            name="authorized_uk",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=3,
                null=True,
                verbose_name="Are you authorized to work in the United Kingdom?",
            ),
        ),
        migrations.AlterField(
            model_name="equalemploymentdata",
            name="authorized_us",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=3,
                null=True,
                verbose_name="Are you authorized to work in the US?",
            ),
        ),
        migrations.AlterField(
            model_name="equalemploymentdata",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Non-Binary", "Non-Binary"),
                    ("Decline to state", "Decline to state"),
                ],
                max_length=20,
                null=True,
                verbose_name="What is your gender?",
            ),
        ),
        migrations.AlterField(
            model_name="equalemploymentdata",
            name="has_disability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("Decline to state", "Decline to state"),
                ],
                max_length=20,
                null=True,
                verbose_name="Do you have a disability?",
            ),
        ),
        migrations.AlterField(
            model_name="equalemploymentdata",
            name="is_lgbtq",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("Decline to state", "Decline to state"),
                ],
                max_length=20,
                null=True,
                verbose_name="Do you identify as LGBTQ+?",
            ),
        ),
        migrations.AlterField(
            model_name="equalemploymentdata",
            name="is_veteran",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("Decline to state", "Decline to state"),
                ],
                max_length=20,
                null=True,
                verbose_name="Are you a veteran?",
            ),
        ),
        migrations.AlterField(
            model_name="equalemploymentdata",
            name="requires_sponsorship",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=3,
                null=True,
                verbose_name="Will you now or in the future require sponsorship for employment visa status?",
            ),
        ),
    ]
