# Generated by Django 5.1.3 on 2024-11-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_resume_s3_key_alter_resume_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="s3_key",
            field=models.CharField(default=132, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
