# Generated by Django 5.1.3 on 2024-11-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_resume_s3_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="s3_key",
        ),
    ]
