# Generated by Django 5.1.3 on 2024-11-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_remove_resume_s3_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="s3_key",
            field=models.CharField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
